<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Democratic-Republican</name>
   <tag></tag>
   <elementGuidId>780d78d0-1b07-4f79-b04e-cfe26acc4386</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(4) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mw-content-text']/div/p[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>57d4ef73-e16e-447b-9f76-d73eb1218e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wiki/Democratic-Republican_Party</value>
      <webElementGuid>acc0a7f0-e8f2-46d8-b5d0-0da376c118a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Democratic-Republican</value>
      <webElementGuid>26325fe4-4494-482d-acbb-9a4d8de6e96c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mw-content-text&quot;)/div[@class=&quot;mw-content-ltr mw-parser-output&quot;]/p[4]/a[1]</value>
      <webElementGuid>b08c8d4e-4f16-447c-bb79-261e4af31ed8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mw-content-text']/div/p[4]/a</value>
      <webElementGuid>72ee7b20-2e42-4ba2-9e77-411922af4210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Democratic-Republican')])[2]</value>
      <webElementGuid>13fdcdbc-f7c0-4ba5-bc50-2211cc88c0cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/wiki/Democratic-Republican_Party')]</value>
      <webElementGuid>ce57bb81-66cc-44d8-9bde-8486d8249c06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]/a</value>
      <webElementGuid>23a1e259-4667-4465-a9ac-a5841b7b359d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wiki/Democratic-Republican_Party' and (text() = 'Democratic-Republican' or . = 'Democratic-Republican')]</value>
      <webElementGuid>6c6958a3-a211-413c-b151-36f1d2d09480</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
