<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Color blind glasses</name>
   <tag></tag>
   <elementGuidId>d70c805d-154c-4ec2-a87d-7f7484fea62a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mw-search-result-heading > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mw-content-text']/div[3]/div[3]/ul/li/table/tbody/tr/td[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d100610c-54b3-4328-9c80-155e3f2ad3b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wiki/Color_blind_glasses</value>
      <webElementGuid>add2e239-4ac9-421d-b1cf-b7f76eb0cba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-serp-pos</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e749deb4-7056-4978-83ea-f14b314caebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Color blind glasses</value>
      <webElementGuid>ec3a34e7-3fda-4e0e-9552-0704178b574f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mw-content-text&quot;)/div[@class=&quot;searchresults&quot;]/div[@class=&quot;mw-search-results-container&quot;]/ul[@class=&quot;mw-search-results&quot;]/li[@class=&quot;mw-search-result mw-search-result-ns-0&quot;]/table[@class=&quot;searchResultImage&quot;]/tbody[1]/tr[1]/td[@class=&quot;searchResultImage-text&quot;]/div[@class=&quot;mw-search-result-heading&quot;]/a[1]</value>
      <webElementGuid>b774ecd5-260f-410f-9639-932322565854</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mw-content-text']/div[3]/div[3]/ul/li/table/tbody/tr/td[2]/div/a</value>
      <webElementGuid>7f4eee03-9871-4c2c-8838-e27999e5f45a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Color blind glasses')]</value>
      <webElementGuid>dd397454-ccc9-41bc-b661-b8c86c9458a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/wiki/Color_blind_glasses')])[2]</value>
      <webElementGuid>fc2bae9a-4d07-4b7c-8553-5440091a5b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/a</value>
      <webElementGuid>1442d417-6ace-40c0-b2a2-11f340880664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wiki/Color_blind_glasses' and (text() = 'Color blind glasses' or . = 'Color blind glasses')]</value>
      <webElementGuid>126abac6-f61e-4bd7-a001-e99c5e4ec744</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
