<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Atom</name>
   <tag></tag>
   <elementGuidId>d3d53252-5cec-4b2f-8be1-cf710d4252a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#feed-atom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='feed-atom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9c2b1084-8466-4d3b-9057-49c4880a5488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/w/index.php?title=Color_blind_glasses&amp;feed=atom&amp;action=history</value>
      <webElementGuid>647bc223-c251-4d38-b0e3-95cf2630569a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>feed-atom</value>
      <webElementGuid>3212eae3-d885-433a-a898-8a87bc4c8491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>alternate</value>
      <webElementGuid>da121235-ad2b-4438-b9bf-6a998c97cd7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>application/atom+xml</value>
      <webElementGuid>7f12f188-69f6-43ab-aced-15d80008d0d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feedlink</value>
      <webElementGuid>5160ff9c-45b0-4b64-abb2-e1f27b4afa30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Atom feed for this page</value>
      <webElementGuid>ad2e57bc-2060-463b-8407-ff7d571031c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Atom</value>
      <webElementGuid>263e40af-939c-4de5-b333-906c6d701150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;feed-atom&quot;)</value>
      <webElementGuid>6b42d6b5-dec4-4f74-a1ee-dc58d6cbcce9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='feed-atom']</value>
      <webElementGuid>7c45f3a7-e00f-42d8-9bd9-d4d3c1c6dd21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='feedlinks']/a</value>
      <webElementGuid>42d0a7e3-ba7e-4943-b34c-7cc42773f840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/w/index.php?title=Color_blind_glasses&amp;feed=atom&amp;action=history')]</value>
      <webElementGuid>cab2d42c-d1ef-47f6-81db-0553799d31f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav[2]/div/div/div/div/div[3]/div[2]/ul/li[3]/a</value>
      <webElementGuid>7cfccf6f-ac97-4c29-bb9a-796123083f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/w/index.php?title=Color_blind_glasses&amp;feed=atom&amp;action=history' and @id = 'feed-atom' and @type = 'application/atom+xml' and @title = 'Atom feed for this page' and (text() = 'Atom' or . = 'Atom')]</value>
      <webElementGuid>50f94c7d-6c0a-4647-acf6-171449336910</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
